name: FinalTECH

author: Final_ROOT

description: About making the world faster

main: io.taraxacum.finaltech.FinalTech

website: https://github.com/zomx127/FinalTECH

version: ${project.version}

api-version: 1.17

depend:
- Slimefun

commands:
  finaltech-copy-card:
    description: Transfer a valid item to a copy card
    usage: /<command>
    permission: finaltech.item.copy-card
  finaltech-item-value:
    description: Show the value of the item
    usage: /<command> <id>
    permission: finaltech.item.value
  finaltech-item-info:
    description: Show info about the item if it's from slimefun
    usage: /<command>
    permission: finaltech.item.info

permissions:
  finaltech.item.value:
    description: Show the value of the item
    default: op
  finaltech.item.copy-card:
    description: Transfer a valid item to a copy card
    default: op
  finaltech.item.info:
    description: Show info about the item if it's from slimefun
    default: true
