name: FinalTECH

author: Final_ROOT

description: About making the world faster

main: io.taraxacum.finaltech.FinalTech

website: https://github.com/zomx127/FinalTECH

version: ${project.version}

api-version: 1.17

depend:
- Slimefun

commands:
  test:
    description: test command
    usage: /<command>
    permission: finaltech.test
